# Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6hfltrh46gs73e6j8p0-a:5432/test_u90s

spring.datasource.username=test_u90s_user
spring.datasource.password=1JZ64I9xgGWzSQQ6bQW76NntcPpVxIUh

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
# Server
server.port=5432


